### ISSUE TITLE
使用此模板编写的论文通过审核了么？

### ISSUE THREAD

**Issue by largeword** [imguozr/NJUPThesis-Bachelor#6]
作者你好，感谢你提供的模板，我想知道使用此模板编写的论文在格式上是否完全符合南邮的论文规定并通过审核

**Comment by gzr-lgtm** [comment]
你好！据我所知，用了模板的同学以及本人的论文并没有收到格式相关的修改要求。:-) 另外，格式查验在南邮并不严格，如果大体格式相差无几的情况下，遇到的更多是按照导师要求进行相应的小幅度修改。希望可以回答你的问题。

**Comment by largeword** [comment]
> 你好！据我所知，用了模板的同学以及本人的论文并没有收到格式相关的修改要求。:-) 另外，格式查验在南邮并不严格，如果大体格式相差无几的情况下，遇到的更多是按照导师要求进行相应的小幅度修改。希望可以回答你的问题。

感谢回复！
