### ISSUE TITLE
能否让附录里面的section标题也显示在目录中

### ISSUE THREAD

**Issue by Steven-AA** [imguozr/NJUPThesis-Bachelor#8]
我在附录里面用 section 来区分多个附录内容，但section的标题并不会在目录里面体现？

需要怎么设置吗？还是我不应该用section命令？

谢谢。

**Comment by gzr-lgtm** [comment]
你好，当前版本中附录中的 section 不会出现在目录里，如果需要修复请将模板要求中的具体格式发在这里。
如果时间紧急，可以在 cls 文件中的 `\newcommand{\thesisappendix}{...}` 中添加命令 `\addtocontents{toc}{\protect\setcounter{tocdepth}{2}}` 来解决。

**Comment by Steven-AA** [comment]
我去看了一眼模板，模板里面只有附录，没有二级标题了，应该是我想多了。

这是附录的要求

> （5）附录编于正文后，与正文连续编页码，每一附录均另页起；
>（6）附录依次用大写正体A，B，C……编序号，黑体，三号。如：附录A；
>（7）附录中的图、表、式、参考文献等与正文分开，用阿拉伯数字另行编序号，注意在数码前冠以附录的序码。如：图A1；表B2；式（C-3）；文献[D5]。

![image](https://user-images.githubusercontent.com/22387129/82633269-426b2180-9c2d-11ea-8e42-dd01498cd3dc.png)

请问，第6点的 顶格的“附录A”怎么实现？

**Comment by gzr-lgtm** [comment]
可以在 cls 文件中自定义命令，配置字号和字体。如果你设置成功了，欢迎提出 PR 来帮助改进本项目 😊

**Comment by Steven-AA** [comment]
等我定稿了，试试看。

顺便，谢谢你的模板，真的帮助非常大，省了好多事情。

**Comment by gzr-lgtm** [comment]
不用客气！如果可以的话，烦请帮忙宣传本项目，让周围同学也来体验一下省事儿的感觉 XD
